# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15cd83888e015356a6cbf63d48729d814928134c27a74bed71f61fecc69dfb06372be109abd0ab2f82787a7e060da44b0041438f6f0dc66af738b0f89cff92dd

test:
  secret_key_base: e7b651fe35cfe59a7f27ad5e348c459e8474b3259f040949107845b78cef57a7e1033fd6b661f2fec5fd7508f905fdb7f3032585293e2509d2b2f0a1a0ba18c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
